### PR TITLE
fix(tabs): line indicator transition bug (#550)

### LINKED ISSUE #550: 套用 `react-activation`  后，Tabs组件初次渲染时下横条样式错乱
版本：3.0.0-rc.7 （之前使用v2 alpha是没问题的）
codesandbox重现不了，初步分析是以下原因(如下图)，麻烦大佬解决，谢谢！

image

image

### PR DESCRIPTION
**Pull request by luo3house**
Fix #550 

`react-activation` set display none for child elements, that causes line transition stops calculate.

In this PR, line transition does calculate by `useUpdateEffect()` after `react-activation` re-shows child elements on mount.

Also fix a potential bug of `type` toggle.
Reproduction: https://stackblitz.com/edit/vitejs-vite-umbtuh
Steps to reproduce: 
- npm i && npm dev
- Click the toggler button at the top
- Then see indicator stucks.

### CODE REVIEW

File: packages/react-vant/src/components/tabs/Tabs.tsx [hunk 1]
```diff
@@ -364,7 +366,11 @@ const Tabs = forwardRef<TabsInstance, TabsProps>((props, ref) => {
 
   return (
     <TabsContext.Provider value={{ props, currentName, scrollIntoView }}>
-      <div ref={root} className={clsx(props.className, bem([props.type]))} style={ props.style }>
```
Comment (luo3house) [inline packages/react-vant/src/components/tabs/Tabs.tsx:367]: linter
